[tool.poetry]
name = "splatter-rebase"
version = "0.1.0"
description = ""
authors = ["Armin Kazemi <arminkz@live.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
conan = "^2.0"



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
